apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      type: result
  template:
    metadata:
      labels:
        type: result
    spec:
      containers:
        - name: result
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
