apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      type: worker
  template:
    metadata:
      labels:
        type: worker
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1
